name: CI
on:
  - pull_request
jobs:
  job1:
    runs-on: ubuntu-latest
    name: build
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
<<<<<<< HEAD
          java-version: "21"
=======
          java-version: "217"
>>>>>>> adb0710 (Update CI workflow to set up JDK 21)
          distribution: "adopt"
      - name: Build and test
        working-directory: .
        run: |
          export SHELL=/bin/bash

          chmod 777 ./gradlew
